name: instagram_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: GB
      fonts:
        - asset: fonts/GilroyBold.ttf
          weight: 700
    - family: GXB
      fonts:
        - asset: fonts/GilroyExtraBold.ttf
          weight: 800
    - family: GH
      fonts:
        - asset: fonts/GilroyHeavy.ttf
          weight: 900
    - family: GL
      fonts:
        - asset: fonts/GilroyLight.ttf
          weight: 300
    - family: GM
      fonts:
        - asset: fonts/GilroyMedium.ttf
          weight: 500
    - family: GR
      fonts:
        - asset: fonts/GilroyRegular.ttf
          weight: 400
    - family: GT
      fonts:
        - asset: fonts/GilroyThin.ttf
          weight: 100
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500
